# Website details
name: TamanBunga Translation - Manga
description: Tempat Baca Manga Garapan TamanBunga
email: email@site.com
author: author
lang: id
locale: id_ID

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: Jakarta/Indonesia
paginateLabel: page
paginate_path: "page/:num"
permalink: /:title
baseurl: https://manga.tamanbungatranslation.my.id

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"
